config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: [:index]
  resources :docs, only: [:index]

  resources :sites, only: [:index, :show] do
    resources :hives, only: [:show]
  end

  resource :dashboard, only: [:show], :controller => "dashboard"

  namespace :dashboard do
    resources :sites, only: [:new, :create, :edit, :update] do
      resources :hives, only: [:new, :create] do
        resources :logs, only: [:new, :create]
      end
    end
  end

  post ':id/follow_site', to: "relationships#follow_site", as: :follow_site
  post ':id/unfollow_site', to: "relationships#unfollow_site", as: :unfollow_site

  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: "sessions#create"
  delete '/logout', to: "sessions#destroy", as: :logout

  root to: 'homes#index'

  namespace :api do
    namespace :v1, defaults: {format: :json} do
      get "sites", to: "sites#index"
      get "sites/:id", to: "sites#show"
      get "users/:user_id/sites", to: "users/sites#index"
    end
  end
end

app/controllers/dashboard/hives_controller.rb
class Dashboard::HivesController < ApplicationController

  def new
    @site = Site.find(params[:site_id])
    @hive = Hive.new
  end

  def create
    @site = Site.find(params[:site_id])
    @hive = @site.hives.new(hive_params)
    if @hive.save
      flash[:success] = "Created a new hive!"
      redirect_to site_hive_path(@hive.site, @hive)
    else
      flash.now[:warning] = @hive.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def hive_params
    params.require(:hive).permit(:name, :description)
  end
end

app/controllers/dashboard/logs_controller.rb
class Dashboard::LogsController < ApplicationController

  def new
    @site = Site.find(params[:site_id])
    if @site.user != current_user
      flash[:warning] = "Not authorized."
      redirect_to root_path
    else
      @hive = Hive.find(params[:hive_id])
      @log = Log.new
    end
  end

  def create
    @site = Site.find(params[:site_id])
    @hive = Hive.find(params[:hive_id])
    @log = @hive.logs.new(log_params)
    if @log.save
      flash[:success] = "Created a new log!"
      redirect_to site_hive_path(@hive.site, @hive)
    else
      flash.now[:warning] = @log.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def log_params
    params.require(:log).permit(:notes, :log_img)
  end
end

app/controllers/dashboard/sites_controller.rb
class Dashboard::SitesController < ApplicationController

  def new
    @site = current_user.sites.new
  end

  def create
    @site = current_user.sites.new(site_params)
    if @site.save
      flash[:success] = "You created a new site!"
      redirect_to site_path(@site)
    else
      flash.now[:warning] = @site.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @site = Site.find(params[:id])
    if @site.user != current_user
      flash[:warning] = "Not authrorized."
      redirect_to root_path
    end
  end

  def update
    @site = Site.find(params[:id])
    if @site.update(site_params)
      flash[:success] = "Site information changed."
      redirect_to site_path(@site)
    end
  end

  private
    def site_params
      params.require(:site).permit(:name,
                                   :description,
                                   :street,
                                   :city,
                                   :state,
                                   :zip,
                                   :longitude,
                                   :latitude,
                                   :status,
                                   :site_img)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :require_login

  def require_login
    unless current_user
      flash[:warning] = "#{view_context.link_to('Login', google_login_path)} before accessing your dashboard."
      redirect_to root_path
    end
  end

  def show
    @sites = current_user.sites
    @sites_following_logs = current_user.logs_of_followed_sites
  end
end

app/views/dashboard/_sites.html.erb
<div class="col-md-offset-1 col-md-4">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Your Hive Sites</h3>
    </div>

    <ul class="list-group">
      <% sites.each do |site| %>
        <li class="list-group-item">
          <%= link_to site.name, site_path(site) %>
          <%= link_to "Edit Site", edit_dashboard_site_path(site), class: "btn btn-default" %>
        </li>
      <% end %>
      <%= link_to "Create a New Site", new_dashboard_site_path, class: "list-group-item text-center" %>
    </ul>
  </div>
</div>

app/views/dashboard/_sites_following.html.erb
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Logs of Sites You Are Following</h3>
    </div>

    <ul class="list-group">
      <% if current_user.following.empty? %>
        <li class="list-group-item">You are not following any sites</li>
      <% elsif sites_following_logs.empty? %>
        <li class="list-group-item">The sites you are following do not have any logs yet</li>
      <% else %>
        <% sites_following_logs.each do |log| %>
          <li class="list-group-item">
            <%= log.created_at.strftime("%B %-d, %Y %l:%M%P") %><br>
            <%= log.hive.name %>: <%= log.notes %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/dashboard/_weather.html.erb
<div class="col-md-offset-1 col-md-10">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Weather For First Site...</h3>
    </div>

    <table class="table table-bordered">
      <tr>
        <% weather_days.each do |day| %>
          <th class="col-md-1"><%= day.date_formatted %></th>
        <% end %>
      </tr>

      <tr>
        <% weather_days.each do |day| %>
          <td class="col-md-1">
            <%= day.summary %><br><br>
            Low: <%= day.temperatureMin %> F<br>
            High: <%= day.temperatureMax %> F</td>
        <% end %>
      </tr>
    </table>
  </div>
</div>

app/views/dashboard/show.html.erb
<h1 class="text-center">Your HiveHealth Dashboard</h1>

<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Map of Your Hive Sites</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div id="dashboard-sites-map" data-user="<%= current_user.id %>">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <%= render partial: "sites", locals: {sites: @sites} %>

  <%= render partial: "sites_following", locals: {sites_following_logs: @sites_following_logs} %>
</div>


<script
    src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAPS_API']%>">
</script>