config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: [:index]
  resources :docs, only: [:index]

  resources :sites, only: [:index, :show] do
    resources :hives, only: [:show]
  end

  resource :dashboard, only: [:show], :controller => "dashboard"

  namespace :dashboard do
    resources :sites, only: [:new, :create, :edit, :update] do
      resources :hives, only: [:new, :create] do
        resources :logs, only: [:new, :create]
      end
    end
  end

  post ':id/follow_site', to: "relationships#follow_site", as: :follow_site
  post ':id/unfollow_site', to: "relationships#unfollow_site", as: :unfollow_site

  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: "sessions#create"
  delete '/logout', to: "sessions#destroy", as: :logout

  root to: 'homes#index'

  namespace :api do
    namespace :v1, defaults: {format: :json} do
      get "sites", to: "sites#index"
      get "sites/:id", to: "sites#show"
      get "users/:user_id/sites", to: "users/sites#index"
    end
  end
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "HiveHealth Home", root_path %></li>
        <li><%= link_to "Hive Sites Map", sites_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <p class="navbar-text"> Hello, <%= current_user.first_name %></p>
          <li><%= link_to "See Your Dashboard", dashboard_path %></li>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", google_login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>