config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: [:index]
  resources :docs, only: [:index]

  resources :sites, only: [:index, :show] do
    resources :hives, only: [:show]
  end

  resource :dashboard, only: [:show], :controller => "dashboard"

  namespace :dashboard do
    resources :sites, only: [:new, :create, :edit, :update] do
      resources :hives, only: [:new, :create] do
        resources :logs, only: [:new, :create]
      end
    end
  end

  post ':id/follow_site', to: "relationships#follow_site", as: :follow_site
  post ':id/unfollow_site', to: "relationships#unfollow_site", as: :unfollow_site

  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: "sessions#create"
  delete '/logout', to: "sessions#destroy", as: :logout

  root to: 'homes#index'

  namespace :api do
    namespace :v1, defaults: {format: :json} do
      get "sites", to: "sites#index"
      get "sites/:id", to: "sites#show"
      get "users/:user_id/sites", to: "users/sites#index"
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end
end

app/views/homes/index.html.erb
<div class="jumbotron">
  <h1>HiveHealth</h1>
  <p>A honeycomb network of bees and beekeepers</p>
  <p><%= link_to "Explore Our Network", sites_path, class: "btn btn-default btn-lg" %></p>
</div>

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail well">
      <img src="https://hd.unsplash.com/photo-1461183479101-6c14cd5299c4" alt="bee-map">
      <div class="caption">
        <h3>See Network of Hive Sites</h3>
        <p>View other bee hives in your area.</p>
        <p><%= link_to "View Hive Sites Map", sites_path, class: "btn btn-primary" %></p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail well">
      <img src="https://hd.unsplash.com/photo-1461532257246-777de18cd58b" alt="login-to-nework">
      <div class="caption">
        <h3>Share Your Hive's Health</h3>
        <p>Become part of a growing network of beekepers.</p>
        <% if current_user %>
          <p><%= link_to "Go to Your Dashboard", dashboard_path, class: "btn btn-primary" %></p>
        <% else %>
          <p><%= link_to "Login with Google", google_login_path, class: "btn btn-primary" %></p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail well">
      <img src="https://hd.unsplash.com/photo-1431605695381-f4a9c3cdd150" alt="login-to-nework">
      <div class="caption">
        <h3>Research Hive Data</h3>
        <p>Use our API to capture hive data over time.</p>
        <p><%= link_to "View API Documentation", docs_path, class: "btn btn-primary" %></p>
      </div>
    </div>
  </div>
</div>

app/views/homes/show.html.erb
<div class="jumbotron">
  <h1>HiveHealth</h1>
  <p>A honeycomb network of bees and beekeepers</p>
  <p><%= link_to "Explore Our Network", sites_path, class: "btn btn-default btn-lg" %></p>
</div>

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail well">
      <img src="https://hd.unsplash.com/photo-1461183479101-6c14cd5299c4" alt="bee-map">
      <div class="caption">
        <h3>See Network of Hive Sites</h3>
        <p>View other bee hives in your area.</p>
        <p><%= link_to "View Hive Sites Map", sites_path, class: "btn btn-primary" %></p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail well">
      <img src="https://hd.unsplash.com/photo-1461532257246-777de18cd58b" alt="login-to-nework">
      <div class="caption">
        <h3>Share Your Hive's Health</h3>
        <p>Become part of a growing network of beekepers.</p>
        <% if current_user %>
          <p><%= link_to "Go to Your Dashboard", dashboard_path, class: "btn btn-primary" %></p>
        <% else %>
          <p><%= link_to "Login with Google", google_login_path, class: "btn btn-primary" %></p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail well">
      <img src="https://hd.unsplash.com/photo-1431605695381-f4a9c3cdd150" alt="login-to-nework">
      <div class="caption">
        <h3>Research Hive Data</h3>
        <p>Use our API to capture hive data over time.</p>
        <p><%= link_to "View API Documentation", sites_path, class: "btn btn-primary" %></p>
      </div>
    </div>
  </div>
</div>