config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: [:index]
  resources :docs, only: [:index]

  resources :sites, only: [:index, :show] do
    resources :hives, only: [:show]
  end

  resource :dashboard, only: [:show], :controller => "dashboard"

  namespace :dashboard do
    resources :sites, only: [:new, :create, :edit, :update] do
      resources :hives, only: [:new, :create] do
        resources :logs, only: [:new, :create]
      end
    end
  end

  post ':id/follow_site', to: "relationships#follow_site", as: :follow_site
  post ':id/unfollow_site', to: "relationships#unfollow_site", as: :unfollow_site

  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: "sessions#create"
  delete '/logout', to: "sessions#destroy", as: :logout

  root to: 'homes#index'

  namespace :api do
    namespace :v1, defaults: {format: :json} do
      get "sites", to: "sites#index"
      get "sites/:id", to: "sites#show"
      get "users/:user_id/sites", to: "users/sites#index"
    end
  end
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :user
  has_many :hives
  has_many :logs, through: :hives

  has_many :follower_relationships, foreign_key: :site_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :user

  has_attached_file :site_img,
                    styles: {
                      thumb: '100x100>',
                      square: '200x200#',
                      medium: '300x300>'
                    },
                    default_url: "/images/site/missing.jpg"

  validates_attachment_content_type :site_img, content_type: /\Aimage\/.*\Z/
  validates :street, uniqueness: { scope: [:city, :state, :zip] }, on: :create
  validates :street, presence: true, on: :create
  validates :city, presence: true, on: :create
  validates :state, presence: true, on: :create
  validates :zip, presence: true, on: :create

  after_save :convert_address_to_long_lat

  def convert_address_to_long_lat
    formatted_address = "#{street}, #{city}, #{state} #{zip}"
    long_lat = Geocoder.coordinates(formatted_address)
    update_column(:longitude, long_lat[1])
    update_column(:latitude, long_lat[0])
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sites
  has_many :hives, through: :sites

  has_many :following_relationships, foreign_key: :user_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :site

  before_create :generate_api_key

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid = auth_info.uid
      new_user.first_name = auth_info.info.first_name
      new_user.last_name = auth_info.info.last_name
      new_user.email = auth_info.info.email
      new_user.token = auth_info.credentials.token
      new_user.expires_at = auth_info.credentials.expires_at
    end
  end

  def generate_api_key
    token = generate_token(self).to_s
    self.api_key = token.to_s
  end

  def generate_new_api_key
    token = generate_token(self).to_s
    update(api_key: token)
  end

  def generate_token(user)
    Digest::SHA2.new << "#{user.uid}#{user.email}#{rand(100000)}"
  end

  def follow(site)
    following_relationships.create(site: site)
  end

  def unfollow(site)
    following_relationships.find_by(site: site).destroy
  end

  def logs_of_followed_sites
    following.map do |hive|
      hive.logs
    end.flatten
  end
end

app/controllers/api/v1/sites_controller.rb
class Api::V1::SitesController < ApiBaseController

  def index
    @sites = Site.all
  end

  def show
    @site = Site.find(params[:id])
  end
end

app/controllers/api/v1/users/sites_controller.rb
class Api::V1::Users::SitesController < ApiBaseController

  def index
    @sites = User.find(params[:user_id]).sites
  end
end

app/controllers/dashboard/sites_controller.rb
class Dashboard::SitesController < ApplicationController

  def new
    @site = current_user.sites.new
  end

  def create
    @site = current_user.sites.new(site_params)
    if @site.save
      flash[:success] = "You created a new site!"
      redirect_to site_path(@site)
    else
      flash.now[:warning] = @site.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @site = Site.find(params[:id])
    if @site.user != current_user
      flash[:warning] = "Not authrorized."
      redirect_to root_path
    end
  end

  def update
    @site = Site.find(params[:id])
    if @site.update(site_params)
      flash[:success] = "Site information changed."
      redirect_to site_path(@site)
    end
  end

  private
    def site_params
      params.require(:site).permit(:name,
                                   :description,
                                   :street,
                                   :city,
                                   :state,
                                   :zip,
                                   :longitude,
                                   :latitude,
                                   :status,
                                   :site_img)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def index
  end

  def show
    @site = Site.find(params[:id])
    @hives = @site.hives
    @weather_days = Weather.forecast_by_location(@site.latitude, @site.longitude)
  end
end

app/views/sites/_hives.html.erb
<div class="col-md-offset-1 col-md-4">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Hives at <%= @site.name %></h3>
    </div>

    <ul class="list-group">
      <% if @hives.empty? %>
        <li class="list-group-item">No hives at this site yet</li>
      <% else %>
        <% @hives.each do |hive| %>
          <li class="list-group-item">
            <%= link_to hive.name, site_hive_path(@site, hive) %>
            <% if @site.user == current_user %>
              <%= link_to "New Log", new_dashboard_site_hive_log_path(@site, hive), class: "new-log-link btn btn-default" %>
            <% end %>
          </li>
        <% end %>
      <% end %>

      <% if @site.user == current_user %>
        <%= link_to "Add a Hive to Your Site", new_dashboard_site_hive_path(@site), class: "list-group-item text-center" %>
      <% end %>
    </ul>

  </div>
</div>

app/views/sites/_site_actions.html.erb
<% if @site.user == current_user %>
  <% if @site.status == "healthy" %>
    <%= link_to "Set Site Status as Sick", dashboard_site_path(@site, site: {status: "sick"}), method: :put, class: "btn btn-danger" %>
  <% else %>
    <%= link_to "Set Site Status as Healthy", dashboard_site_path(@site, site: {status: "healthy"}), method: :put, class: "btn btn-success" %>
  <% end %>
  <%= link_to "Edit Site Information", edit_dashboard_site_path(@site), class: "btn btn-default" %>
<% else %>
  <% if current_user.following_ids.include?(@site.id) %>
    <%= link_to "Unfollow This Site's Hives", unfollow_site_path, remote: true, class: "btn btn-primary", id: "unfollow-button", data: { id: "#{@site.id}" }, method: :post %>
  <% else %>
    <%= link_to "Follow This Site's Hives", follow_site_path, remote: true, class: "btn btn-primary", id: "follow-button", data: { id: "#{@site.id}" }, method: :post %>
  <% end %>
<% end %>

app/views/sites/_weather.html.erb
<div class="col-md-offset-1 col-md-10">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Forecast For <%= site.name %></h3>
    </div>

    <table class="table table-bordered">
      <tr>
        <% weather_days.each do |day| %>
          <th class="col-md-1"><%= day.date_formatted %></th>
        <% end %>
      </tr>

      <tr>
        <% weather_days.each do |day| %>
          <td class="col-md-1">
            Low: <%= day.temperatureMin.round(1) %> F<br>
            High: <%= day.temperatureMax.round(1) %> F<br><br>
            <%= day.summary %></td>
        <% end %>
      </tr>
    </table>
  </div>
</div>

app/views/sites/index.html.erb
<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <div class="well well-sm">
      <h3 class="text-center">Locations of All HiveHealth Hives</h3>
      <h4 class="text-center"><span class="healthy">Green</span> sites are healthy hives, and <span class="sick">red</span> sites are at risk.</h4>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <div class="panel panel-default">
      <div class="panel-body">
        <div id="all-sites-map">
        </div>
      </div>
    </div>
  </div>
</div>

<script
    src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAPS_API']%>">
</script>

app/views/sites/show.html.erb
<h1 class="text-center"><%= @site.name %></h1>

<div class="row">
  <div class="col-md-offset-1 col-md-10">
      <div class="well col-md-12">
        <div id="site-show-map" data-id="<%= @site.id %>">
        </div>

        <h3>About <%= @site.name %>:</h3>
        <p><%= @site.description %></p>

        <%= image_tag @site.site_img.url(:medium), class: "site-image" %>

        <div class="site-actions">
          <%= render partial: "site_actions", locals: {site: @site} %>
        </div>
      </div>
  </div>
</div>

<div class="row">
  <%= render partial: "weather", locals: {weather_days: @weather_days, site: @site} %>
</div>

<div class="row">
  <%= render partial: "hives", locals: {site: @site, hives: @hives} %>
</div>

<script
    src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAPS_API']%>">
</script>